export const SONGS_ALL = [].concat(SONGS_1950, SONGS_1960, SONGS_1970, SONGS_1980)

const SONGS_1950 = [
  { "id": "1950-0001", "title": "Aaja Re Ab Mera Dil Pukara", "film": "Aah", "artists": [] },
  { "id": "1950-0002", "title": "Aaja Re Pardesi", "film": "Madhumati", "artists": [] },
  { "id": "1950-0003", "title": "Aaja Sanam", "film": "Chori Chori", "artists": [] },
  { "id": "1950-0004", "title": "Achcha Ji Main Haari Chalo Maan Jaao", "film": "Kala Pani", "artists": [] },
  { "id": "1950-0005", "title": "Adha Hai Chandrama", "film": "Navrang", "artists": [] },
  { "id": "1950-0006", "title": "Ae Mere Dil Kahin Aur Chal", "film": "Daag", "artists": [] },
  { "id": "1950-0007", "title": "Ae Meri Topi Palat Ke Aa", "film": "Funtoosh", "artists": [] },
  { "id": "1950-0008", "title": "Aye Dil Mujhe Bata De", "film": "Bhai Bhai", "artists": [] },
  { "id": "1950-0009", "title": "Ai Dil Hai Mushkil Jeena Yahaan", "film": "C.I.D.", "artists": [] },
  { "id": "1950-0010", "title": "Ankhon Hi Ankhon Mein Ishara Ho Gaya", "film": "C.I.D.", "artists": [] },
  { "id": "1950-0011", "title": "Awaara Hoon", "film": "Awara", "artists": [] },
  { "id": "1950-0012", "title": "Aye Maalik Tere Bande Hum", "film": "Do Aankhen Barah Haath", "artists": [] },
  { "id": "1950-0013", "title": "Babu Samjho Ishare", "film": "Chalti Ka Naam Gaadi", "artists": [] },
  { "id": "1950-0014", "title": "Babuji Dheere Chalna", "film": "Aar Paar", "artists": [] },
  { "id": "1950-0015", "title": "Badi Der Bhai", "film": "Basant Bahar", "artists": [] },
  { "id": "1950-0016", "title": "Bholi Soorat Dil Ke Khote", "film": "Albela", "artists": [] },
  { "id": "1950-0017", "title": "Cat Mane Billi", "film": "Dilli Ka Thug", "artists": [] },
  { "id": "1950-0018", "title": "Chhod Do Aanchal Zamana Kya Kahe Ga", "film": "Paying Guest", "artists": [] },
  { "id": "1950-0019", "title": "De Di Hamein Aazadi", "film": "Jagriti", "artists": [] },
  { "id": "1950-0020", "title": "Denewala Jab Bhi Deta", "film": "Funtoosh", "artists": [] },
  { "id": "1950-0021", "title": "Dil Deke Dekho", "film": "Title Song", "artists": [] },
  { "id": "1950-0022", "title": "Dil Ka Khilona Hai Toot Gaya", "film": "Goonj Uthi Shehnai", "artists": [] },
  { "id": "1950-0023", "title": "Dukh Bhare Din Beete Re", "film": "Mother India", "artists": [] },
  { "id": "1950-0024", "title": "Dukhi Mann Mere", "film": "Funtoosh", "artists": [] },
  { "id": "1950-0025", "title": "Duniya Ke Rakhwale", "film": "Baiju Bawra", "artists": [] },
  { "id": "1950-0026", "title": "Duniya Mein Hum Aaye Hain", "film": "Mother India", "artists": [] },
  { "id": "1950-0027", "title": "Dil Mein Chhupake Pyar Le Chale", "film": "Aan", "artists": [] },
  { "id": "1950-0028", "title": "Eena Mina Dika", "film": "Aasha", "artists": [] },
  { "id": "1950-0029", "title": "Ek Ladki Bheegi Bhaagi Si", "film": "Chalti Ka Naam Gaadi", "artists": [] },
  { "id": "1950-0030", "title": "Ek Pardesi Mera Dil Le Gaya", "film": "Phagun", "artists": [] },
  { "id": "1950-0031", "title": "Gore Gore O Banke Chore", "film": "Samadhi", "artists": [] },
  { "id": "1950-0032", "title": "Haal Kaisa Hai Janaab Ka", "film": "Chalti Ka Naam Gaadi", "artists": [] },
  { "id": "1950-0033", "title": "Ham Aapki Aankhon Me", "film": "Pyaasa", "artists": [] },
  { "id": "1950-0034", "title": "Hum Aap Ki Ankhon Mein", "film": "Pyaasa", "artists": [] },
  { "id": "1950-0035", "title": "Hum Laaye Hain Toofan Se Kashti Nikaal Ke", "film": "Jagriti", "artists": [] },
  { "id": "1950-0036", "title": "Hum The Woh Thi", "film": "Chalti Ka Naam Gaadi", "artists": [] },
  { "id": "1950-0037", "title": "Hum To Mohabbat Karega", "film": "Dilli Ka Thug", "artists": [] },
  { "id": "1950-0038", "title": "Hum Tujhse Mohabbat Kar Ke", "film": "Awara", "artists": [] },
  { "id": "1950-0039", "title": "Ichak Dana Beechak Dana", "film": "Shree 420", "artists": [] },
  { "id": "1950-0040", "title": "Jata Kaha Hai Deewane", "film": "C.I.D.", "artists": [] },
  { "id": "1950-0041", "title": "Jaane Kya Tune Kahi", "film": "Pyaasa", "artists": [] },
  { "id": "1950-0042", "title": "Jaane Woh Kaise Log", "film": "Pyaasa", "artists": [] },
  { "id": "1950-0043", "title": "Jab Aane Wale Aate Hain", "film": "Madhosh", "artists": [] },
  { "id": "1950-0044", "title": "Kadam Kadam Badhaye Jaa", "film": "Samadhi", "artists": [] },
  { "id": "1950-0045", "title": "Kahin Pe Nigahen Kahin Pe Nishana", "film": "C.I.D.", "artists": [] },
  { "id": "1950-0046", "title": "Kisi Ki Muskurahaton Pe", "film": "Anari", "artists": [] },
  { "id": "1950-0047", "title": "Kitna Badal Gaya Insaan", "film": "Nastik", "artists": [] },
  { "id": "1950-0048", "title": "Kusoor Aapka Huzoor", "film": "Bahar", "artists": [] },
  { "id": "1950-0049", "title": "Man Dole Mera Tan Dole", "film": "Nagin", "artists": [] },
  { "id": "1950-0050", "title": "Mera Juta Hai Japani", "film": "Shree 420", "artists": [] },
  { "id": "1950-0051", "title": "Milte Hi Nazar", "film": "New Delhi", "artists": [] },
  { "id": "1950-0052", "title": "Mudh Mudh Ke Na Dekh", "film": "Shree 420", "artists": [] },
  { "id": "1950-0053", "title": "Mera Naam Chin Chin Chu", "film": "Howrah Bridge", "artists": [] },
  { "id": "1950-0054", "title": "Nakhrewali", "film": "New Delhi", "artists": [] },
  { "id": "1950-0055", "title": "Pyar Hua Iqrar Hua", "film": "Shree 420", "artists": [] },
  { "id": "1950-0056", "title": "Ramaiya Vastavaiya", "film": "Shree 420", "artists": [] },
  { "id": "1950-0057", "title": "Reshmi Shalwar Kurta", "film": "Naya Daur", "artists": [] },
  { "id": "1950-0058", "title": "Sab Kuchh Seekha Hamne", "film": "Anari", "artists": [] },
  { "id": "1950-0059", "title": "Saathi Haath Badhana", "film": "Naya Daur", "artists": [] },
  { "id": "1950-0060", "title": "Shaam Dhale Khidki Tale", "film": "Albela", "artists": [] },
  { "id": "1950-0061", "title": "Saiyan Dil Mein Aana Re", "film": "Bahar", "artists": [] },
  { "id": "1950-0062", "title": "Sar Jo Tera Chakraye", "film": "Pyaasa", "artists": [] },
  { "id": "1950-0063", "title": "Sun Sun Sun Sun Zaalima", "film": "Aar Paar", "artists": [] },
  { "id": "1950-0064", "title": "Tadbeer Se Bigdi Hui Taqdeer Bana Le", "film": "Baazi", "artists": [] },
  { "id": "1950-0065", "title": "Tu Ganga Ki Mauj", "film": "Baiju Bawra", "artists": [] },
  { "id": "1950-0066", "title": "Tu Hindu Banega Na Musalman Banega", "film": "Dhool Ka Phool", "artists": [] },
  { "id": "1950-0067", "title": "Tu Pyar Ka Sagar Hai", "film": "Seema", "artists": [] },
  { "id": "1950-0068", "title": "Tum Jiyo Hazaaron Saal", "film": "Sujata", "artists": [] },
  { "id": "1950-0069", "title": "Tum Sang Preet Lagai Rasiya", "film": "New Delhi", "artists": [] },
  { "id": "1950-0070", "title": "Tumsa Nahin Dekha", "film": "Title Song", "artists": [] },
  { "id": "1950-0071", "title": "Ye Lo Main Haari Piya", "film": "Aar Paar", "artists": [] },
  { "id": "1950-0072", "title": "Yeh Desh Hai Veer", "film": "Naya Daur", "artists": [] },
  { "id": "1950-0073", "title": "Yeh Mera Diwanapan Hai", "film": "Yahudi", "artists": [] },
  { "id": "1950-0074", "title": "Yaad Aane Wale Phir Yaad Aa Rahe Hai", "film": "Anmol Ratan", "artists": [] },
  { "id": "1950-0075", "title": "Yeh Raat Bheegi Bheegi", "film": "Chori Chori", "artists": [] }
];


const SONGS_1960 = [
  { "id": "1960-0001", "title": "Aa Jaan-E-Jaan", "film": "Intaqam", "artists": [] },
  { "id": "1960-0002", "title": "Aage Bhi Jaane Na Tu", "film": "Waqt", "artists": [] },
  { "id": "1960-0003", "title": "Aaja Aai Bahar", "film": "Rajkumar", "artists": [] },
  { "id": "1960-0004", "title": "Aajkal Tere Mere Pyar Ke Charche", "film": "Brahmachari", "artists": [] },
  { "id": "1960-0005", "title": "Aane Se Uske Aaye Bahar", "film": "Jeene Ki Raah", "artists": [] },
  { "id": "1960-0006", "title": "Aap Ki Nazron Ne Samjha", "film": "Anpadh", "artists": [] },
  { "id": "1960-0007", "title": "Ab Tumhare Hawale Watan Sathiyon", "film": "Haqeeqat", "artists": [] },
  { "id": "1960-0008", "title": "Abhi Na Jao Chhodkar", "film": "Hum Dono", "artists": [] },
  { "id": "1960-0009", "title": "Ae Mohabbat Zindabad", "film": "Mughal-e-Azam", "artists": [] },
  { "id": "1960-0010", "title": "Ai Ai Aa Suku Suku", "film": "Kashmir Ki Kali", "artists": [] },
  { "id": "1960-0011", "title": "Ajeeb Dastan Hai Yeh", "film": "Dil Apna Aur Preet Parai", "artists": [] },
  { "id": "1960-0012", "title": "Aji Rooth Kar Ab Kahan Jaiyega", "film": "Arzoo", "artists": [] },
  { "id": "1960-0013", "title": "Andaz Mera Mastana", "film": "Dil Apna Aur Preet Parai", "artists": [] },
  { "id": "1960-0014", "title": "Aye Mere Pyaare Watan", "film": "Kabuliwala", "artists": [] },
  { "id": "1960-0015", "title": "Baar Baar Din Ye Aaye", "film": "Farz", "artists": [] },
  { "id": "1960-0016", "title": "Badan Pe Sitare Lapete", "film": "Prince", "artists": [] },
  { "id": "1960-0017", "title": "Baharon Phool Barsao", "film": "Suraj", "artists": [] },
  { "id": "1960-0018", "title": "Bar Bar Dekho", "film": "China Town", "artists": [] },
  { "id": "1960-0019", "title": "Bedardi Balma Tujhko", "film": "Arzoo", "artists": [] },
  { "id": "1960-0020", "title": "Bekarar Karke Hume", "film": "Bees Saal Baad", "artists": [] },
  { "id": "1960-0021", "title": "Bekhudi Mein Sanam", "film": "Hasina Maan Jayegi", "artists": [] },
  { "id": "1960-0022", "title": "Bindiya Chamkegi", "film": "Do Raaste", "artists": [] },
  { "id": "1960-0023", "title": "Bol Gori Bol Tera Kaun Piya", "film": "Milan", "artists": [] },
  { "id": "1960-0024", "title": "Chalo Ek Baar Phir Se", "film": "Gumrah", "artists": [] },
  { "id": "1960-0025", "title": "Chand Si Mehbooba Ho Meri", "film": "Himalay Ki God Mein", "artists": [] },
  { "id": "1960-0026", "title": "Chaudhvin Ka Chand Ho", "film": "Title Song", "artists": [] },
  { "id": "1960-0027", "title": "Chup Gaye Saare Nazaare", "film": "Do Raaste", "artists": [] },
  { "id": "1960-0028", "title": "Deewanon Se Ye Mat Poocho", "film": "Upkar", "artists": [] },
  { "id": "1960-0029", "title": "Dhoondo Dhoondo Re Sajna", "film": "Gunga Jumna", "artists": [] },
  { "id": "1960-0030", "title": "Dil Apna Aur Preet Parai", "film": "Title Song", "artists": [] },
  { "id": "1960-0031", "title": "Dil Ke Jharokhe Mein", "film": "Brahmachari", "artists": [] },
  { "id": "1960-0032", "title": "Dooriyan Nazdikiyan Ban Gayi", "film": "Duniya", "artists": [] },
  { "id": "1960-0033", "title": "Ehsaan Tera Hoga", "film": "Kashmir Ki Kali", "artists": [] },
  { "id": "1960-0034", "title": "Ek Tu Jo Mila/Na Mila", "film": "Himalay Ki God Mein", "artists": [] },
  { "id": "1960-0035", "title": "Gairon Pe Karam", "film": "Aakhen", "artists": [] },
  { "id": "1960-0036", "title": "Gumnaam Hai Koi", "film": "Gumnaam", "artists": [] },
  { "id": "1960-0037", "title": "Ham Tere Pyar Mein", "film": "Dil Ek Mandir", "artists": [] },
  { "id": "1960-0038", "title": "Haule Haule Chalo More Sajna", "film": "Sawan Ki Ghata", "artists": [] },
  { "id": "1960-0039", "title": "Hothon Pe Sacchai Rehti Hai", "film": "Jis Desh Mein Ganga Behti Hai", "artists": [] },
  { "id": "1960-0040", "title": "Roop Tera Mastana", "film": "Aradhana", "artists": [] },
  { "id": "1960-0041", "title": "Baghon Mein Bahar Hai", "film": "Aradhana", "artists": [] },
  { "id": "1960-0042", "title": "Chanda Hai Tu Mera Suraj Hai Tu", "film": "Aradhana", "artists": [] },
  { "id": "1960-0043", "title": "Mere Sapno Ki Rani", "film": "Aradhana", "artists": [] },
  { "id": "1960-0044", "title": "Kora Kagaz Tha Yeh Man Mera", "film": "Aradhana", "artists": [] },
  { "id": "1960-0045", "title": "Saphal Hogi Teri Aradhana", "film": "Aradhana", "artists": [] },
  { "id": "1960-0046", "title": "Gunguna Rahe Hai Bhawre", "film": "Aradhana", "artists": [] },
  { "id": "1960-0047", "title": "Mere Man Ki Ganga", "film": "Sangam", "artists": [] },
  { "id": "1960-0048", "title": "Dost Dost Na Raha", "film": "Sangam", "artists": [] },
  { "id": "1960-0049", "title": "Har Dil Jo Pyaar Karega", "film": "Sangam", "artists": [] },
  { "id": "1960-0050", "title": "Yeh Mera Prem Patra", "film": "Sangam", "artists": [] },
  { "id": "1960-0051", "title": "Main Kya Karoon Ram", "film": "Sangam", "artists": [] },
  { "id": "1960-0052", "title": "Aaj Phir Jeene Ki Tamanna", "film": "Guide", "artists": [] },
  { "id": "1960-0053", "title": "Din Dhal Jaaye Gaata Rahe Mera Dil", "film": "Guide", "artists": [] },
  { "id": "1960-0054", "title": "Kya Se Kya Ho Gaya", "film": "Guide", "artists": [] },
  { "id": "1960-0055", "title": "Piya Tose Naina Laage Re", "film": "Guide", "artists": [] },
  { "id": "1960-0056", "title": "Wahan Kaun Hai Tera", "film": "Guide", "artists": [] },
  { "id": "1960-0057", "title": "Neele Gagan Ke Tale", "film": "Hamraaz", "artists": [] },
  { "id": "1960-0058", "title": "Na Muh Chupaake Jiyo", "film": "Hamraaz", "artists": [] },
  { "id": "1960-0059", "title": "Tum Agar Saath Dene Ka", "film": "Hamraaz", "artists": [] },
  { "id": "1960-0060", "title": "Kisi Patthar Ki Moorat Se", "film": "Hamraaz", "artists": [] },
  { "id": "1960-0061", "title": "Chahoonga Main Tujhe Saanj Savere", "film": "Dosti", "artists": [] },
  { "id": "1960-0062", "title": "Meri Dosti Mera Pyar", "film": "Dosti", "artists": [] },
  { "id": "1960-0063", "title": "Rahi Manwa Dukh Ki Chinta", "film": "Dosti", "artists": [] },
  { "id": "1960-0064", "title": "Mera To Jo Bhi Kadam", "film": "Dosti", "artists": [] },
  { "id": "1960-0065", "title": "Jaanewalo Zara", "film": "Dosti", "artists": [] },
  { "id": "1960-0066", "title": "Gudiya Humse Roothi Rahogi", "film": "Dosti", "artists": [] },
  { "id": "1960-0067", "title": "Hum Kaale Hain To", "film": "Gumnaam", "artists": [] },
  { "id": "1960-0068", "title": "Hum Tum Yug Yug Se", "film": "Milan", "artists": [] },
  { "id": "1960-0069", "title": "Insaaf Ki Dagar Pe", "film": "Gunga Jumna", "artists": [] },
  { "id": "1960-0070", "title": "Isharon Isharon Men Dil Lenewale", "film": "Kashmir Ki Kali", "artists": [] },
  { "id": "1960-0071", "title": "Iss Duniya Mein Jeena Ho Toh Sunlo Meri Baat", "film": "Gumnaam", "artists": [] },
  { "id": "1960-0072", "title": "Jaaiye Aap Kahaan Jaayenge", "film": "Mere Sanam", "artists": [] },
  { "id": "1960-0073", "title": "Jhumka Gira Re", "film": "Mera Saaya", "artists": [] },
  { "id": "1960-0074", "title": "Jiya O Jiya", "film": "Jab Pyar Kisi Se Hota Hai", "artists": [] },
  { "id": "1960-0075", "title": "Jo Wada Kiya Wo", "film": "Taj Mahal", "artists": [] },
  { "id": "1960-0076", "title": "Kankariya Maar Ke Jagaya", "film": "Himalay Ki God Mein", "artists": [] },
  { "id": "1960-0077", "title": "Kashmir Ki Kali Hoon Main", "film": "Kashmir Ki Kali", "artists": [] },
  { "id": "1960-0078", "title": "Kasme Waade Pyar Wafa", "film": "Upkar", "artists": [] },
  { "id": "1960-0079", "title": "Khoya Khoya Chand", "film": "Kala Bazar", "artists": [] },
  { "id": "1960-0080", "title": "Lag Jaa Gale Ki Phir Ye Haseen Raat Ho Na Ho", "film": "Woh Kaun Thi?", "artists": [] },
  { "id": "1960-0081", "title": "Lakhon Hai Nigah Mein", "film": "Phir Wohi Dil Laya Hoon", "artists": [] },
  { "id": "1960-0082", "title": "Likhe Jo Khat Tujhe", "film": "Kanyadaan", "artists": [] },
  { "id": "1960-0083", "title": "Main Gaoon Tum So Jao", "film": "Brahmachari", "artists": [] },
  { "id": "1960-0084", "title": "Main Pyar Ka Rahi Hoon", "film": "Ek Musafir Ek Haseena", "artists": [] },
  { "id": "1960-0085", "title": "Mast Baharon Ka Main Aashiq", "film": "Farz", "artists": [] },
  { "id": "1960-0086", "title": "Mera Naam Karega Roshan", "film": "Ek Phool Do Mali", "artists": [] },
  { "id": "1960-0087", "title": "Mera Saaya Saath", "film": "Mera Saaya", "artists": [] },
  { "id": "1960-0088", "title": "Mera Yaar Bana Hai Dulha", "film": "Chaudhvin Ka Chand", "artists": [] },
  { "id": "1960-0089", "title": "Mere Desh Ki Dharti", "film": "Gulshan Bawra", "artists": [] },
  { "id": "1960-0090", "title": "Mere Mehboob Tujhe", "film": "Title Song", "artists": [] },
  { "id": "1960-0091", "title": "Milti Hai Zindagi Mein Mohabbat", "film": "Aakhen", "artists": [] },
  { "id": "1960-0092", "title": "Mohe Panghat Pe", "film": "Mughal-e-Azam", "artists": [] },
  { "id": "1960-0093", "title": "Na Na Karte Pyar Tumhin Se", "film": "Jab Jab Phool Khile", "artists": [] },
  { "id": "1960-0094", "title": "Naina Barase Rimjhim Rimjhim", "film": "Woh Kaun Thi?", "artists": [] },
  { "id": "1960-0095", "title": "Naina Lad Jaihen", "film": "Gunga Jumna", "artists": [] },
  { "id": "1960-0096", "title": "Nainon Mein Badra", "film": "Mera Saaya", "artists": [] },
  { "id": "1960-0097", "title": "Neele Gagan Ke Tale", "film": "Hamraaz", "artists": [] },
  { "id": "1960-0098", "title": "O Haseena Zulfonwali Jaane Jahan", "film": "Teesri Manzil", "artists": [] },
  { "id": "1960-0099", "title": "O Mere Sona Re Sona Re", "film": "Teesri Manzil", "artists": [] },
  { "id": "1960-0100", "title": "O Sanam Tere Ho Gayen Hum", "film": "Ayee Milan Ki Bela", "artists": [] },
  { "id": "1960-0101", "title": "Parde Mein Rahne Do", "film": "Shikar", "artists": [] },
  { "id": "1960-0102", "title": "Pardesiyon Se Na Ankhiyan Milana", "film": "Jab Jab Phool Khile", "artists": [] },
  { "id": "1960-0103", "title": "Patthar Ke Sanam", "film": "Title Song", "artists": [] },
  { "id": "1960-0104", "title": "Pukarta Chala Hoon Main", "film": "Mere Sanam", "artists": [] },
  { "id": "1960-0105", "title": "Raat Kaa Samaa Jhume Chandramaa", "film": "Ziddi", "artists": [] },
  { "id": "1960-0106", "title": "Raha Gardishon Mein Hardum", "film": "Do Badan", "artists": [] },
  { "id": "1960-0107", "title": "Ram Kare Aisa Ho Jaye", "film": "Milan", "artists": [] },
  { "id": "1960-0108", "title": "Sau Saal Pehle", "film": "Jab Pyar Kisi Se Hota Hai", "artists": [] },
  { "id": "1960-0109", "title": "Sayonara Sayonara", "film": "Love In Tokyo", "artists": [] },
  { "id": "1960-0110", "title": "Taarif Karoon Kya Uski", "film": "Kashmir Ki Kali", "artists": [] },
  { "id": "1960-0111", "title": "Tauba Yeh Matwali Chaal", "film": "Patthar Ke Sanam", "artists": [] },
  { "id": "1960-0112", "title": "Tera Mera Pyaar Amar", "film": "Asli-Naqli", "artists": [] },
  { "id": "1960-0113", "title": "Tere Ghar Ke Samne", "film": "Title Song", "artists": [] },
  { "id": "1960-0114", "title": "Tujhe Jeevan Ki Dor Se", "film": "Asli-Naqli", "artists": [] },
  { "id": "1960-0115", "title": "Tujhko Mera Pyar Pukare", "film": "Gumrah", "artists": [] },
  { "id": "1960-0116", "title": "Tumhin Meri Mandir", "film": "Khandan", "artists": [] },
  { "id": "1960-0117", "title": "Tumko Hamari Umar Lag Jaye", "film": "Ayee Milan Ki Bela", "artists": [] },
  { "id": "1960-0118", "title": "Tumne Pukara Aur Hum Chale Aaye", "film": "Rajkumar", "artists": [] },
  { "id": "1960-0119", "title": "Tumse Achchha Kaun Hai", "film": "Janwar", "artists": [] },
  { "id": "1960-0120", "title": "Ye Hai Reshmi Zulfon Ka Andhera", "film": "Mere Sanam", "artists": [] },
  { "id": "1960-0121", "title": "Ye Samaa Samaa Hai Pyar Ka", "film": "Jab Jab Phool Khile", "artists": [] },
  { "id": "1960-0122", "title": "Yeh Aankhen Uff Yun Maa", "film": "Jab Pyar Kisi Se Hota Hai", "artists": [] },
  { "id": "1960-0123", "title": "Yeh Reshmi Zulfen", "film": "Do Raaste", "artists": [] },
  { "id": "1960-0124", "title": "Bade Miya Diwane", "film": "Shagird", "artists": [] },
  { "id": "1960-0125", "title": "Dil Wil Pyar Wyar", "film": "Shagird", "artists": [] },
  { "id": "1960-0126", "title": "Woh Hain Zara Khafa Khafa", "film": "Shagird", "artists": [] },
  { "id": "1960-0127", "title": "Ruk Jaa Aye Hawa, Tham Jaa Aye Bahaar", "film": "Shagird", "artists": [] },
  { "id": "1960-0128", "title": "Yeh Dil Na Hota Bechara", "film": "Jewel Thief", "artists": [] },
  { "id": "1960-0130", "title": "Rulake Gaya Sapna Mera", "film": "Jewel Thief", "artists": [] },
  { "id": "1960-0131", "title": "Aasman Ke Neeche", "film": "Jewel Thief", "artists": [] },
  { "id": "1960-0132", "title": "Dil Pukare Aa Re", "film": "Jewel Thief", "artists": [] },
  { "id": "1960-0133", "title": "Hothon Mein Aisi Baat", "film": "Jewel Thief", "artists": [] },
  { "id": "1960-0134", "title": "Akele Akele Kahan Ja Rahe Ho", "film": "An Evening in Paris", "artists": [] },
  { "id": "1960-0135", "title": "Raat Ke Hamsafar", "film": "An Evening in Paris", "artists": [] },
  { "id": "1960-0136", "title": "Aasman Se Aaya Farishta", "film": "An Evening in Paris", "artists": [] },
  { "id": "1960-0137", "title": "An Evening in Paris", "film": "An Evening in Paris", "artists": [] },
  { "id": "1960-0138", "title": "Main Chali Main Chali", "film": "Padosan", "artists": [] },
  { "id": "1960-0139", "title": "Bhai Battur", "film": "Padosan", "artists": [] },
  { "id": "1960-0140", "title": "Mere Samne Wali Khidki", "film": "Padosan", "artists": [] },
  { "id": "1960-0141", "title": "Ek Chatur Naar", "film": "Padosan", "artists": [] },
  { "id": "1960-0142", "title": "Kehana Hai.. Kehana Hai Tumse", "film": "Padosan", "artists": [] },
  { "id": "1960-0143", "title": "Mere Bhole Balam", "film": "Padosan", "artists": [] }
];


const SONGS_1970 = [
  { "id": "1970-0001", "title": "Aadmi Musafir Hai", "film": "Apnapan", "artists": [] },
  { "id": "1970-0002", "title": "Aaj Madhosh Hua Jaye Re", "film": "Sharmilee", "artists": [] },
  { "id": "1970-0003", "title": "Aaj Mausam Bada Beimaan Hai", "film": "Loafer", "artists": [] },
  { "id": "1970-0004", "title": "Aaj Na Chodenge", "film": "Kati Patang", "artists": [] },
  { "id": "1970-0005", "title": "Aap Ke Kamre Mein Koi Rehta Hain", "film": "Yaadon Ki Baaraat", "artists": [] },
  { "id": "1970-0006", "title": "Aapki Mehki Huyi Zulf Ko", "film": "Trishul", "artists": [] },
  { "id": "1970-0007", "title": "Aap Yahan Aaye Kisliye", "film": "Kal Aaj Aur Kal", "artists": [] },
  { "id": "1970-0008", "title": "Aati Rahengi Baharen", "film": "Kasme Vaade", "artists": [] },
  { "id": "1970-0009", "title": "Ab Chahe Ma Roothe Yaa Baba", "film": "Daag: A Poem of Love", "artists": [] },
  { "id": "1970-0010", "title": "Achchha To Hum Chalte Hai", "film": "Aan Milo Sajna", "artists": [] },
  { "id": "1970-0011", "title": "Bachna Ae Haseeno", "film": "Hum Kisise Kum Naheen", "artists": [] },
  { "id": "1970-0012", "title": "Bana Ke Kyon Bigada Re", "film": "Zanjeer", "artists": [] },
  { "id": "1970-0013", "title": "Bhanware Ki Gunjan", "film": "Kal Aaj Aur Kal", "artists": [] },
  { "id": "1970-0014", "title": "Bharat Ka Rehnewaala", "film": "Purab Aur Paschim", "artists": [] },
  { "id": "1970-0015", "title": "Bhor Bhaye Panghat Pe", "film": "Satyam Shivam Sundaram", "artists": [] },
  { "id": "1970-0016", "title": "Chadti Jawani Meri Chaal Mastani", "film": "Caravan", "artists": [] },
  { "id": "1970-0017", "title": "Chal Chal Chal Mere Saathi", "film": "Haathi Mere Saathi", "artists": [] },
  { "id": "1970-0018", "title": "Chal Dariya Mein Doob Jaye", "film": "Prem Kahani", "artists": [] },
  { "id": "1970-0019", "title": "Chalo Re Doli Uthao", "film": "Jaani Dushman", "artists": [] },
  { "id": "1970-0020", "title": "Chand Mera Dil Chandni Ho Tum", "film": "Hum Kisise Kum Naheen", "artists": [] },
  { "id": "1970-0021", "title": "Chandamama Se Pyaara Mere Mama", "film": "Noorie", "artists": [] },
  { "id": "1970-0022", "title": "Dafliwale Dafli Baja", "film": "Sargam", "artists": [] },
  { "id": "1970-0023", "title": "Deewane Hai Deewanon Ko", "film": "Zanjeer", "artists": [] },
  { "id": "1970-0024", "title": "Dhal Gaya Din Ho Gayi Sham", "film": "Humjoli", "artists": [] },
  { "id": "1970-0025", "title": "Dil Sachaa Aur Chehra Jhutha", "film": "Sachaa Jhutha", "artists": [] },
  { "id": "1970-0026", "title": "Dil To Hai Dil", "film": "Muqaddar Ka Sikandar", "artists": [] },
  { "id": "1970-0027", "title": "Dilbar Dil Se Pyare", "film": "Caravan", "artists": [] },
  { "id": "1970-0028", "title": "Dilbar Jani Chali Hawa Mastani", "film": "Haathi Mere Saathi", "artists": [] },
  { "id": "1970-0029", "title": "Do Lafzon Ki Hai Dil Ki Kahaani", "film": "The Great Gambler", "artists": [] },
  { "id": "1970-0030", "title": "Dum Maro Dum Mit Jaye Gham", "film": "Hare Rama Hare Krishna", "artists": [] },
  { "id": "1970-0031", "title": "Ek Main Aur Ek Tu", "film": "Khel Khel Mein", "artists": [] },
  { "id": "1970-0032", "title": "Fakira Chal Chala Chal", "film": "Fakira", "artists": [] },
  { "id": "1970-0033", "title": "Gaadi Bula Rahi Hai", "film": "Dost", "artists": [] },
  { "id": "1970-0034", "title": "Gapoochi Gapoochi Gam Gam", "film": "Trishul", "artists": [] },
  { "id": "1970-0035", "title": "Ghungaroo Ki Tarah", "film": "Chor Machaye Shor", "artists": [] },
  { "id": "1970-0036", "title": "Goria Kahan Tera Desh", "film": "Caravan", "artists": [] },
  { "id": "1970-0037", "title": "Gunmaster G9", "film": "Surakshaa", "artists": [] },
  { "id": "1970-0038", "title": "Hai Agar Dushman", "film": "Hum Kisise Kum Naheen", "artists": [] },
  { "id": "1970-0039", "title": "Hai Na Bolo Bolo", "film": "Andaz", "artists": [] },
  { "id": "1970-0040", "title": "Ham To Chale Pardes", "film": "Sargam", "artists": [] },
  { "id": "1970-0041", "title": "Hare Rama Hare Krishna", "film": "Hare Rama Hare Krishna", "artists": [] },
  { "id": "1970-0042", "title": "Hay Hay Yeh Majboor", "film": "Roti Kapda Aur Makaan", "artists": [] },
  { "id": "1970-0043", "title": "Haye Re Haye", "film": "Humjoli", "artists": [] },
  { "id": "1970-0044", "title": "Holi Ke Din", "film": "Sholay", "artists": [] },
  { "id": "1970-0045", "title": "Hum Ko To Yaara Teri Yaari Jaan", "film": "Hum Kisise Kum Naheen", "artists": [] },
  { "id": "1970-0046", "title": "Humne Tumko Dekha", "film": "Khel Khel Mein", "artists": [] },
  { "id": "1970-0047", "title": "Hum Tum Ek Kamre Mein Band Ho", "film": "Bobby", "artists": [] },
  { "id": "1970-0048", "title": "Humko Tumse Ho Gaya Hai Pyar", "film": "Amar Akbar Anthony", "artists": [] },
  { "id": "1970-0049", "title": "Husn Hazir Hai", "film": "Laila Majnu", "artists": [] },
  { "id": "1970-0050", "title": "Husn Ke Lakhon Rang", "film": "Johny Mera Naam", "artists": [] },
  { "id": "1970-0051", "title": "Jab Bhi Jee Chaahe", "film": "Daag: A Poem of Love", "artists": [] },
  { "id": "1970-0052", "title": "Jai Santoshi Maa", "film": "Jai Santoshi Maa", "artists": [] },
  { "id": "1970-0053", "title": "Jate Ho Jaane Jaana", "film": "Parvarish", "artists": [] },
  { "id": "1970-0054", "title": "Jeevan Se Bhari", "film": "Safar", "artists": [] },
  { "id": "1970-0055", "title": "Jhilmil Sitaron Ka Aangan Hoga", "film": "Jeevan Mrityu", "artists": [] },
  { "id": "1970-0056", "title": "Jhoot Bole Kauva Kate", "film": "Bobby", "artists": [] },
  { "id": "1970-0057", "title": "Jiska Mujhe Tha Intezar", "film": "Don", "artists": [] },
  { "id": "1970-0058", "title": "Jo Tumko Ho Pasand", "film": "Safar", "artists": [] },
  { "id": "1970-0059", "title": "Kab Tak Na Dogi Dil", "film": "Kahani Kismat Ki", "artists": [] },
  { "id": "1970-0060", "title": "Kabhi Kabhie Mere Dil Mein", "film": "Kabhi Kabhie", "artists": [] },
  { "id": "1970-0061", "title": "Kahin Door Jab", "film": "Anand", "artists": [] },
  { "id": "1970-0062", "title": "Kanchi Re Kanchi", "film": "Hare Rama Hare Krishna", "artists": [] },
  { "id": "1970-0063", "title": "Karti Hu Tumhara Vrat Main, Sweekar Karo Maa", "film": "Jai Santoshi Maa", "artists": [] },
  { "id": "1970-0064", "title": "Karwaten Badalte Rahe", "film": "Aap Ki Kasam", "artists": [] },
  { "id": "1970-0065", "title": "Kasme Vaade Nibhayenge Hum", "film": "Kasme Vaade", "artists": [] },
  { "id": "1970-0066", "title": "Kehdoon Tumhe", "film": "Deewaar", "artists": [] },
  { "id": "1970-0067", "title": "Khilte Hain Gul Yahan", "film": "Sharmilee", "artists": [] },
  { "id": "1970-0068", "title": "Khullam Khulla Pyaar Karenge Hum Dono", "film": "Khel Khel Mein", "artists": [] },
  { "id": "1970-0069", "title": "Khush Rahe Tu Sada", "film": "Khilona", "artists": [] },
  { "id": "1970-0070", "title": "Khushiyan Hi Khushiyan", "film": "Dulhan Wahi Jo Piya Man Bhaye", "artists": [] },
  { "id": "1970-0071", "title": "Koi Haseena", "film": "Sholay", "artists": [] },
  { "id": "1970-0072", "title": "Koi Jab Tumhara Hriday Tod De", "film": "Purab Aur Paschim", "artists": [] },
  { "id": "1970-0073", "title": "Koi Saheri Babu", "film": "Loafer", "artists": [] },
  { "id": "1970-0074", "title": "Kuchh Kehta Hai Ye Saawan", "film": "Mera Gaon Mera Desh", "artists": [] },
  { "id": "1970-0075", "title": "Kya Hua Tera Wada", "film": "Hum Kisise Kum Naheen", "artists": [] },
  { "id": "1970-0076", "title": "Le Jayenge Le Jayenge", "film": "Chor Machaye Shor", "artists": [] },
  { "id": "1970-0077", "title": "Le Toh Aaye Ho Hame Sapno", "film": "Dulhan Wahi Jo Piya Man Bhaye", "artists": [] },
  { "id": "1970-0078", "title": "Leena O Leena Dil Toone Cheena", "film": "Swarg Narak", "artists": [] },
  { "id": "1970-0079", "title": "Lekar Hum Deewana Dil", "film": "Yaadon Ki Baaraat", "artists": [] },
  { "id": "1970-0080", "title": "Maar Diya Jaye", "film": "Mera Gaon Mera Desh", "artists": [] },
  { "id": "1970-0081", "title": "Madad Karo Santoshi Mata", "film": "Jai Santoshi Maa", "artists": [] },
  { "id": "1970-0082", "title": "Mai Toh Aaratee Utaru Re Santoshee Mata Kee", "film": "Jai Santoshi Maa", "artists": [] },
  { "id": "1970-0083", "title": "Main Hoon Don", "film": "Don", "artists": [] },
  { "id": "1970-0084", "title": "Main Jat Yamla Pagla", "film": "Pratigya", "artists": [] },
  { "id": "1970-0085", "title": "Main Na Bhoolunga", "film": "Roti Kapda Aur Makaan", "artists": [] },
  { "id": "1970-0086", "title": "Main Pal Do Pal Ka Shayar Hoon", "film": "Kabhi Kabhie", "artists": [] },
  { "id": "1970-0087", "title": "Main Shayar To Nahin", "film": "Bobby", "artists": [] },
  { "id": "1970-0088", "title": "Main Tere Ishq Mein Marna Jaau Kahi", "film": "Loafer", "artists": [] },
  { "id": "1970-0089", "title": "Main Tulsi Tere Aangan Ki", "film": "Title song", "artists": [] },
  { "id": "1970-0090", "title": "Maine Tere Liye", "film": "Anand", "artists": [] },
  { "id": "1970-0091", "title": "Mat Ro Mat Ro Aaj Radhike", "film": "Jai Santoshi Maa", "artists": [] },
  { "id": "1970-0092", "title": "Mausam Hain Gaane Ka", "film": "Surakshaa", "artists": [] },
  { "id": "1970-0093", "title": "Mehbooba Mehbooba", "film": "Sholay", "artists": [] },
  { "id": "1970-0094", "title": "Mehngai Mar Gayi", "film": "Roti Kapda Aur Makaan", "artists": [] },
  { "id": "1970-0095", "title": "Mere Dil Mein Aaj Kya Hai", "film": "Daag: A Poem of Love", "artists": [] },
  { "id": "1970-0096", "title": "Meri Pyari Behaniya", "film": "Sachaa Jhutha", "artists": [] },
  { "id": "1970-0097", "title": "Mohabbat Bade Kam Ki", "film": "Trishul", "artists": [] },
  { "id": "1970-0098", "title": "Motiyon Ki Ladi Hoon Main", "film": "Loafer", "artists": [] },
  { "id": "1970-0099", "title": "Na Jiya Lage Na", "film": "Anand", "artists": [] },
  { "id": "1970-0100", "title": "Na Koi Umang Hai", "film": "Kati Patang", "artists": [] },
  { "id": "1970-0101", "title": "Naach Meri Bulbul", "film": "Roti", "artists": [] },
  { "id": "1970-0102", "title": "Nafrat Ki Duniya Ko Chhod Ke", "film": "Haathi Mere Saathi", "artists": [] },
  { "id": "1970-0103", "title": "O Meri Sharmilee", "film": "Sharmilee", "artists": [] },
  { "id": "1970-0104", "title": "O Saathi Re Tere Bina", "film": "Muqaddar Ka Sikandar", "artists": [] },
  { "id": "1970-0105", "title": "O Sheronwali", "film": "Suhaag", "artists": [] },
  { "id": "1970-0106", "title": "Pal Bhar Ke Liye", "film": "Johny Mera Naam", "artists": [] },
  { "id": "1970-0107", "title": "Parbat Ke Us Paar", "film": "Sargam", "artists": [] },
  { "id": "1970-0108", "title": "Pardah Hai Pardah", "film": "Amar Akbar Anthony", "artists": [] },
  { "id": "1970-0109", "title": "Peene Wale Ko Peene Ka Bahana", "film": "Haath Ki Safai", "artists": [] },
  { "id": "1970-0110", "title": "Phoolon Ka Taron Ka", "film": "Hare Rama Hare Krishna", "artists": [] },
  { "id": "1970-0111", "title": "Piya Tu Ab To Aaja", "film": "Caravan", "artists": [] },
  { "id": "1970-0112", "title": "Purva Suhani Aayi Re", "film": "Purab Aur Paschim", "artists": [] },
  { "id": "1970-0113", "title": "Pyar Deewana Hota Hai", "film": "Kati Patang", "artists": [] },
  { "id": "1970-0114", "title": "Qadar Tune Na Jani", "film": "Noorie", "artists": [] },
  { "id": "1970-0115", "title": "Ram Ji Ki Nikli Sawari", "film": "Sargam", "artists": [] },
  { "id": "1970-0116", "title": "Re Mama Re Mama Re", "film": "Andaz", "artists": [] },
  { "id": "1970-0117", "title": "Rote Hue Ate Hain Sab", "film": "Muqaddar Ka Sikandar", "artists": [] },
  { "id": "1970-0118", "title": "Ruk Jana O Jana Humse", "film": "Warrant", "artists": [] },
  { "id": "1970-0119", "title": "Salaam-e-Ishq Meri Jaan", "film": "Muqaddar Ka Sikandar", "artists": [] },
  { "id": "1970-0120", "title": "Satyam Shivam Sundaram", "film": "Satyam Shivam Sundaram", "artists": [] },
  { "id": "1970-0121", "title": "Shirdi Wale Sai Baba", "film": "Amar Akbar Anthony", "artists": [] },
  { "id": "1970-0122", "title": "Sona Lai Ja Re", "film": "Mera Gaon Mera Desh", "artists": [] },
  { "id": "1970-0123", "title": "Sunja Aa Thandi Hawa", "film": "Haathi Mere Saathi", "artists": [] },
  { "id": "1970-0124", "title": "Sun Ke Teri Pukar", "film": "Fakira", "artists": [] },
  { "id": "1970-0125", "title": "Taiyabali Pyar Ka Dushman", "film": "Amar Akbar Anthony", "artists": [] },
  { "id": "1970-0126", "title": "Tera Mujhse Hain Pehle Ka Nata Koi", "film": "Aa Gale Lag Jaa", "artists": [] },
  { "id": "1970-0127", "title": "Tere Chehre Mein Woh Jaadu Hai", "film": "Dharmatama", "artists": [] },
  { "id": "1970-0128", "title": "Tere Kaaran Mere Saajan", "film": "Aan Milo Sajna", "artists": [] },
  { "id": "1970-0129", "title": "Tere Sang Pyar Main Nahin Todna", "film": "Nagin", "artists": [] },
  { "id": "1970-0130", "title": "Teri Rab Ne Bana Di Jodi", "film": "Suhaag", "artists": [] },
  { "id": "1970-0131", "title": "Tum Ne Kisi Se Kabhi Pyaar Kiya Hai", "film": "Dharmatama", "artists": [] },
  { "id": "1970-0132", "title": "Wada Kar Le Sajna", "film": "Haath Ki Safai", "artists": [] },
  { "id": "1970-0133", "title": "Yaadon Ki Baaraat Nikli Hai", "film": "Yaadon Ki Baaraat", "artists": [] },
  { "id": "1970-0134", "title": "Yaha Waha Jaha Taha Mat Puchho Kaha Kaha Hai", "film": "Jai Santoshi Maa", "artists": [] },
  { "id": "1970-0135", "title": "Yari Hai Imaan Mera", "film": "Zanjeer", "artists": [] },
  { "id": "1970-0136", "title": "Yashomati Maiya Se Bole Nandlala", "film": "Satyam Shivam Sundaram", "artists": [] },
  { "id": "1970-0137", "title": "Yeh Dosti", "film": "Sholay", "artists": [] },
  { "id": "1970-0138", "title": "Yeh Hai Bombay Nagaria", "film": "Don", "artists": [] },
  { "id": "1970-0139", "title": "Yeh Jo Mohabbat Hai", "film": "Kati Patang", "artists": [] },
  { "id": "1970-0140", "title": "Yeh Ladka Hai Allah Kaisa Hai", "film": "Hum Kisise Kum Naheen", "artists": [] },
  { "id": "1970-0141", "title": "Yeh Lal Rang Kab Mujhe Chhodega", "film": "Prem Nagar", "artists": [] },
  { "id": "1970-0142", "title": "Yeh Mera Dil", "film": "Don", "artists": [] },
  { "id": "1970-0143", "title": "Yeh Public Hai", "film": "Roti", "artists": [] },
  { "id": "1970-0144", "title": "Yeh Shaam Mastani", "film": "Kati Patang", "artists": [] },
  { "id": "1970-0145", "title": "Yunhi Tum Mujhse Baat Karti Ho", "film": "Sachaa Jhutha", "artists": [] },
  { "id": "1970-0146", "title": "Zindagi Ek Safar Hai Suhana", "film": "Andaz", "artists": [] },
  { "id": "1970-0147", "title": "Zindagi Ka Safar", "film": "Safar", "artists": [] },
  { "id": "1970-0148", "title": "Zindagi Kaisi Hai Paheli", "film": "Anand", "artists": [] },
  { "id": "1970-0149", "title": "Zuban Pe Dard Bhari Dastaan Chali Aayi", "film": "Maryada", "artists": [] }
];


const SONGS_1980 = [
  { "id": "1980-0001", "title": "Dil Deewana", "film": "Maine Pyar Kiya", "artists": [] },
  { "id": "1980-0002", "title": "Akele Hain To Kya Gum Hai", "film": "Qayamat Se Qayamat Tak", "artists": [] },
  { "id": "1980-0003", "title": "Chhookar Mere Man Ko Kiya Toone Kya Ishaara", "film": "Yaarana", "artists": [] },
  { "id": "1980-0004", "title": "Mere Rang Mein Rangane Wali", "film": "Maine Pyar Kiya", "artists": [] },
  { "id": "1980-0005", "title": "Mein Teri Mohabbat Mein", "film": "Tridev", "artists": [] },
  { "id": "1980-0006", "title": "Tumko Dekha To Yeh Khayal Aaya", "film": "Saath Saath", "artists": [] },
  { "id": "1980-0007", "title": "Aye Mere Humsafar", "film": "Qayamat Se Qayamat Tak", "artists": [] },
  { "id": "1980-0008", "title": "Jaane Do Na", "film": "Saagar", "artists": [] },
  { "id": "1980-0009", "title": "Dilber Mere Kab Tak Mujhe", "film": "Satte Pe Satta", "artists": [] },
  { "id": "1980-0010", "title": "Gazab Ka Hai Din", "film": "Qayamat Se Qayamat Tak", "artists": [] },
  { "id": "1980-0011", "title": "Dekho Maine Dekha Hai", "film": "Love Story", "artists": [] },
  { "id": "1980-0012", "title": "Kaate Nahin Kat Te", "film": "Mr. India", "artists": [] },
  { "id": "1980-0013", "title": "Sun Sahiba Sun", "film": "Ram Teri Ganga Maili", "artists": [] },
  { "id": "1980-0014", "title": "Aaja Sham Hone Aayi", "film": "Maine Pyar Kiya", "artists": [] },
  { "id": "1980-0015", "title": "Tu Tu Hai Wahi", "film": "Yeh Vaada Raha", "artists": [] },
  { "id": "1980-0016", "title": "Aap Jaisa Koi", "film": "Qurbani", "artists": [] },
  { "id": "1980-0017", "title": "Tu Rootha To Main", "film": "Jawaani", "artists": [] },
  { "id": "1980-0018", "title": "Jane Kaise Kab Kahan", "film": "Shakti", "artists": [] },
  { "id": "1980-0019", "title": "Pyar Mujh Se Jo Kiya Tumne", "film": "Saath Saath", "artists": [] },
  { "id": "1980-0020", "title": "Saagar Jaisi Aankohonwali", "film": "Saagar", "artists": [] },
  { "id": "1980-0021", "title": "Tum Itna Jo Muskura Rahe Ho", "film": "Arth", "artists": [] },
  { "id": "1980-0022", "title": "Aate Jaate Haste Gaate", "film": "Maine Pyar Kiya", "artists": [] },
  { "id": "1980-0023", "title": "Jeena Hai Pyar Mein Jeena", "film": "Love Love Love", "artists": [] },
  { "id": "1980-0024", "title": "Mohabbat Hai Kya Cheez", "film": "Prem Rog", "artists": [] },
  { "id": "1980-0025", "title": "Shayad Meri Shaadi Ka Khayal", "film": "Souten", "artists": [] },
  { "id": "1980-0026", "title": "Ungli Mein Angoothi (Part 1)", "film": "Ram Avtar", "artists": [] },
  { "id": "1980-0027", "title": "Roz Roz Aankhon Tale", "film": "Jeeva", "artists": [] },
  { "id": "1980-0028", "title": "Dard-E-Dil Dard-E-Jigar", "film": "Karz", "artists": [] },
  { "id": "1980-0029", "title": "Tu Mera Hero Hain", "film": "Hero", "artists": [] },
  { "id": "1980-0030", "title": "Maine Pyar Kiya", "film": "Maine Pyar Kiya", "artists": [] },
  { "id": "1980-0031", "title": "Ae Ri Pawan", "film": "Bemisal", "artists": [] },
  { "id": "1980-0032", "title": "Hume Tumse Pyar Kitna", "film": "Kudrat", "artists": [] },
  { "id": "1980-0033", "title": "Sheesha Ho Ya Dil Ho Aakhir Tut Jata Hai", "film": "Aasha", "artists": [] },
  { "id": "1980-0034", "title": "Jab Se Tumko Dekha", "film": "Kaalia", "artists": [] },
  { "id": "1980-0035", "title": "Tumse Milke", "film": "Parinda", "artists": [] },
  { "id": "1980-0036", "title": "Neele Neele Ambar Par", "film": "Kalakaar", "artists": [] },
  { "id": "1980-0037", "title": "Humein Aur Jeene Ki Chahat", "film": "Agar Tum Na Hote", "artists": [] },
  { "id": "1980-0038", "title": "Samundar Mein Nahake", "film": "Pukar", "artists": [] },
  { "id": "1980-0039", "title": "Lagi Aag Sawan Ki", "film": "Chandni", "artists": [] },
  { "id": "1980-0040", "title": "Ye Ladki Zarasi Deewani Lagati Hai", "film": "Love Story", "artists": [] },
  { "id": "1980-0041", "title": "Badal Yun Garajta Hai", "film": "Betaab", "artists": [] },
  { "id": "1980-0042", "title": "Ae Dil-e-Nadaan", "film": "Razia Sultan", "artists": [] },
  { "id": "1980-0043", "title": "Yeh Tera Ghar Yeh Mera Ghar", "film": "Saath Saath", "artists": [] },
  { "id": "1980-0044", "title": "Hum Bane Tum Bane", "film": "Ek Duuje Ke Liye", "artists": [] },
  { "id": "1980-0045", "title": "Phir Chhidi Raat", "film": "Bazaar", "artists": [] },
  { "id": "1980-0046", "title": "Solah Baras Ki Baali Umar", "film": "Ek Duuje Ke Liye", "artists": [] },
  { "id": "1980-0047", "title": "Naino Mein Sapna", "film": "Himmatwala", "artists": [] },
  { "id": "1980-0048", "title": "Main Solah Baras Ki", "film": "Karz", "artists": [] },
  { "id": "1980-0049", "title": "Aaya Mausam Dosti Ka", "film": "Maine Pyar Kiya", "artists": [] },
  { "id": "1980-0050", "title": "Jhuki Jhuki Si Nazar", "film": "Arth", "artists": [] },
  { "id": "1980-0051", "title": "Tere Mere Honthon Pe", "film": "Chandni", "artists": [] },
  { "id": "1980-0052", "title": "Yeh Kahan Aa Gaye Hum", "film": "Silsila", "artists": [] },
  { "id": "1980-0053", "title": "Tera Naam Liya", "film": "Ram Lakhan", "artists": [] },
  { "id": "1980-0054", "title": "De De Pyar De", "film": "Sharaabi", "artists": [] },
  { "id": "1980-0055", "title": "Gali Gali Mein Firta Hai Tu Kyun", "film": "Tridev", "artists": [] },
  { "id": "1980-0056", "title": "Jaane De Jaane De Mujhe Jaana", "film": "Shahenshah", "artists": [] },
  { "id": "1980-0057", "title": "Har Kisi Ko Nahi Milta", "film": "Janbaaz", "artists": [] },
  { "id": "1980-0058", "title": "Julie Julie Johny Ka Dil Tumpe Aaya", "film": "Jeete Hain Shaan Se", "artists": [] },
  { "id": "1980-0059", "title": "Mere Pyar Ki Umar", "film": "Waaris", "artists": [] },
  { "id": "1980-0060", "title": "Jab Hum Jawan Honge", "film": "Betaab", "artists": [] },
  { "id": "1980-0061", "title": "Tarzan My Tarzan", "film": "Adventures of Tarzan", "artists": [] },
  { "id": "1980-0062", "title": "Dekha Ek Khwab", "film": "Silsila", "artists": [] },
  { "id": "1980-0063", "title": "Aaj Rapat Jaayen To", "film": "Namak Halaal", "artists": [] },
  { "id": "1980-0064", "title": "Saagar Kinare Dil Ye Pukare", "film": "Saagar", "artists": [] },
  { "id": "1980-0065", "title": "Pyar Mein Dil Pe", "film": "Mahaan", "artists": [] },
  { "id": "1980-0066", "title": "Chotisi Kahani Se", "film": "Ijaazat", "artists": [] },
  { "id": "1980-0067", "title": "Tere Mere Beech Mein", "film": "Ek Duuje Ke Liye", "artists": [] },
  { "id": "1980-0068", "title": "Jab Chhaye Mera Jadoo", "film": "Lootmaar", "artists": [] },
  { "id": "1980-0069", "title": "Mera Kuchh Saman", "film": "Ijaazat", "artists": [] },
  { "id": "1980-0070", "title": "Pyar Hamara Amar Rahega", "film": "Muddat", "artists": [] },
  { "id": "1980-0071", "title": "Kabootar Ja Ja Ja", "film": "Maine Pyar Kiya", "artists": [] },
  { "id": "1980-0072", "title": "Tere Jaisa Yaar Kahan", "film": "Yaarana", "artists": [] },
  { "id": "1980-0073", "title": "Aap Ke Aa Jane Se", "film": "Khudgarz", "artists": [] },
  { "id": "1980-0074", "title": "Kya Dekhte Ho Surat Tumhari", "film": "Qurbani", "artists": [] },
  { "id": "1980-0075", "title": "Mere Pyaar Ki Umar Ho Itni Sanam", "film": "Waaris", "artists": [] },
  { "id": "1980-0076", "title": "In Aankhon Ki Masti", "film": "Umrao Jaan", "artists": [] },
  { "id": "1980-0077", "title": "Teri Yaad Aa Rahi Hai", "film": "Love Story", "artists": [] },
  { "id": "1980-0078", "title": "Sheher Mein Charcha Hai", "film": "Aas Paas", "artists": [] },
  { "id": "1980-0079", "title": "Keh Do Ki Tum Ho Meri", "film": "Teezab", "artists": [] },
  { "id": "1980-0080", "title": "Jaane Kya Baat Hai Neend Nahi Aati", "film": "Sunny", "artists": [] },
  { "id": "1980-0081", "title": "Hum Tumhein Itna Pyar Karange", "film": "Bees Saal Baad", "artists": [] },
  { "id": "1980-0082", "title": "Lambi Judai", "film": "Hero", "artists": [] },
  { "id": "1980-0083", "title": "Aisa Sama Na Hota", "film": "Zameen Aasmaan", "artists": [] },
  { "id": "1980-0084", "title": "Jab Jab Teri Surat Dekhun", "film": "Janbaaz", "artists": [] },
  { "id": "1980-0085", "title": "Mere Jeevan Saathi", "film": "Ek Duuje Ke Liye", "artists": [] },
  { "id": "1980-0086", "title": "Dil Cheez Kya Hai", "film": "Umrao Jaan", "artists": [] },
  { "id": "1980-0087", "title": "Angrezi Men Kahate Hain Ke I Love You", "film": "Khud-Daar", "artists": [] },
  { "id": "1980-0088", "title": "Wada Na Tod", "film": "Dil Tujhko Diya", "artists": [] },
  { "id": "1980-0089", "title": "Mausam Pyar Ka Rang Badalta Rahe", "film": "Sitamgar", "artists": [] },
  { "id": "1980-0090", "title": "Aaj Phir Tum Pe Pyar Aaya", "film": "Dayavan", "artists": [] },
  { "id": "1980-0091", "title": "Koi Yeh Kaise Bataye", "film": "Arth", "artists": [] },
  { "id": "1980-0092", "title": "Chandni O Meri Chandni", "film": "Chandni", "artists": [] },
  { "id": "1980-0093", "title": "Who Kagaz Ki Kashti", "film": "Aaj", "artists": [] },
  { "id": "1980-0094", "title": "Tumse Milkar Na Jane Kyun", "film": "Pyar Jhukta Nahin", "artists": [] },
  { "id": "1980-0095", "title": "Tera Saath Hai Kitna Pyara", "film": "Janbaaz", "artists": [] },
  { "id": "1980-0096", "title": "Jab Chaha Yaara Tumne", "film": "Zabardast", "artists": [] },
  { "id": "1980-0097", "title": "Zindagi Pyar Ka Geet Hai", "film": "Souten", "artists": [] },
  { "id": "1980-0098", "title": "Tum Jo Chale Gaye To Hogi Badi Kharabi", "film": "Aas Paas", "artists": [] },
  { "id": "1980-0099", "title": "Ye Lo Kagaz Ye Lo Kalam", "film": "Mera Lahoo", "artists": [] },
  { "id": "1980-0100", "title": "Tune O Rangile", "film": "Kudrat", "artists": [] },
  { "id": "1980-0101", "title": "Chalo Bulawa Aaya Hai", "film": "Avtaar", "artists": [] },
  { "id": "1980-0102", "title": "Silli Hawa Chhoo Gayi", "film": "Libaas", "artists": [] },
  { "id": "1980-0103", "title": "Jimmy Jimmy Aaja Aaja", "film": "Disco Dancer", "artists": [] },
  { "id": "1980-0104", "title": "Huzoor Is Kadar", "film": "Masoom", "artists": [] },
  { "id": "1980-0105", "title": "Phool Gulab Ka", "film": "Biwi Ho To Aisi", "artists": [] },
  { "id": "1980-0106", "title": "Main Tum Mein Sama Jaun", "film": "Raaste Pyar Ke", "artists": [] },
  { "id": "1980-0107", "title": "Pyar Mein Dil Pe Maar Goli", "film": "Mahaan", "artists": [] },
  { "id": "1980-0108", "title": "Jawani Janeman", "film": "Namak Halaal", "artists": [] },
  { "id": "1980-0109", "title": "Rote Rote Hasna Seekho", "film": "Andhaa Kanoon", "artists": [] },
  { "id": "1980-0110", "title": "Chhodenge Hum Na Tera Saath", "film": "Marte Dum Tak", "artists": [] },
  { "id": "1980-0111", "title": "Mere Peeko Mujhse Roothi", "film": "Ghulami", "artists": [] },
  { "id": "1980-0112", "title": "Jaan Jab Jab Teri Yaad", "film": "All Rounder", "artists": [] },
  { "id": "1980-0113", "title": "Raat Baaqi Baat Baaqi", "film": "Namak Halaal", "artists": [] },
  { "id": "1980-0114", "title": "Oh Maria", "film": "Saagar", "artists": [] },
  { "id": "1980-0115", "title": "Patthar Ke Sanam Kuchh Bol Zara", "film": "Watan Ke Rakhwale", "artists": [] },
  { "id": "1980-0116", "title": "Kisi Nazar Ko Tera Intezar", "film": "Aitbaar", "artists": [] },
  { "id": "1980-0117", "title": "Aaj Kal Yaad Kuch Aur Rahata Nahin", "film": "Nagina", "artists": [] },
  { "id": "1980-0118", "title": "Khamosh Sa Afsana", "film": "Libaas", "artists": [] },
  { "id": "1980-0119", "title": "Aap Ka Khat Mila", "film": "Sharda", "artists": [] },
  { "id": "1980-0120", "title": "Behke Behke Yeh Jazbaat", "film": "Aap Ke Saath", "artists": [] },
  { "id": "1980-0121", "title": "Tere Liye Palkon Ki Jhalar", "film": "Harjaee", "artists": [] },
  { "id": "1980-0122", "title": "Mere Samne Tu Din Raat Rahe", "film": "Bees Saal Baad", "artists": [] },
  { "id": "1980-0123", "title": "Aur Is Dil Mein Kya Rakhha Hai", "film": "Imaandaar", "artists": [] },
  { "id": "1980-0124", "title": "Zoo Zoo Zoobie Zoooby", "film": "Dance Dance", "artists": [] },
  { "id": "1980-0125", "title": "Dikhai Diye Yun", "film": "Bazaar", "artists": [] },
  { "id": "1980-0126", "title": "Neela Aasman So Gaya", "film": "Silsila", "artists": [] },
  { "id": "1980-0127", "title": "Pyar Kabhi Kam Nahi Karna", "film": "Prem Pratigyaa", "artists": [] },
  { "id": "1980-0128", "title": "Mere Pyar Ki Awaz Pe Chali Aana", "film": "Raaj Mahal", "artists": [] },
  { "id": "1980-0129", "title": "Tere Khushboo Mein Base Khat", "film": "Arth", "artists": [] },
  { "id": "1980-0130", "title": "Inteha Ho Gayi Intezaar Ki", "film": "Sharaabi", "artists": [] },
  { "id": "1980-0131", "title": "Tu Is Tarah Se Meri Zindagi Mein", "film": "Aap To Aise Na The", "artists": [] },
  { "id": "1980-0132", "title": "Yaad Aa Raha Hai", "film": "Disco Dancer", "artists": [] },
  { "id": "1980-0133", "title": "Dushman Na Kare Dost Ne Wo Kaam Kiyaa Hai", "film": "Aakhir Kyon", "artists": [] },
  { "id": "1980-0134", "title": "Nindya Se Jaagi Bahaar", "film": "Hero", "artists": [] },
  { "id": "1980-0135", "title": "My Name is Lakhan", "film": "Ram Lakhan", "artists": [] },
  { "id": "1980-0136", "title": "Tirchi Topewale", "film": "Tridev", "artists": [] },
  { "id": "1980-0137", "title": "Tumhe Apna Saathi Banane Se Pehle", "film": "Pyar Jhukta Nahin", "artists": [] },
  { "id": "1980-0138", "title": "Disco Station Disco", "film": "Haathkadi", "artists": [] },
  { "id": "1980-0139", "title": "Mehke Huye Tere Lab Ke Gulab", "film": "Jaisi karni Waisi Bharni", "artists": [] },
  { "id": "1980-0140", "title": "Apni To Jaisi Taise", "film": "Laawaris", "artists": [] },
  { "id": "1980-0141", "title": "Raah Pe Rahte Hain", "film": "Namkeen", "artists": [] },
  { "id": "1980-0142", "title": "Mujhe Naulakha Manga De Re", "film": "Sharaabi", "artists": [] },
  { "id": "1980-0143", "title": "Chanda Dekhe Chanda", "film": "Jhoothi", "artists": [] }
];
